### ISSUE TITLE
Security: Add CodeQL workflow

### ISSUE THREAD

**Issue by makubacki** [microsoft/mu_feature_uefi_variable#21]
Add a CodeQL workflow to the repo for `VariablePkg` so the results are available in GitHub Code Scanning and in the [`Actions`](https://github.com/microsoft/mu_feature_uefi_variable/actions/new) page.

**Comment by ar1936** [comment]
Hi @makubacki , This is my first open source project. so could you please help me to understand this ?

**Comment by makubacki** [comment]
> Hi @makubacki , This is my first open source project. so could you please help me to understand this ?

Hello. What would you like to know? Are you trying to understand what this issue is tracking specifically?
